version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample: 
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
      - run:
          command: pip install -r src/requirements.txt
          name: Install Deps
      - python/save-cache
      - save_cache:
      paths:
        - ./venv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          command: ./manage.py test
          name: Test

